# Generated by Django 5.2.15 on 2026-06-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MOTORBIKE', 'Boda'), ('MINI', 'Mini'), ('STANDARD', 'Standard'), ('XL', 'XL')], max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('DRIVING_LICENSE', 'Driving license'), ('PSV_BADGE', 'PSV badge'), ('LOGBOOK', 'Logbook'), ('INSPECTION_CERT', 'Inspection certificate'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='pricing.vehicletype')),
            ],
            options={
                'unique_together': {('vehicle_type', 'doc_type')},
            },
        ),
    ]
