# Generated by Django 5.2.15 on 2026-06-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_retaxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='code',
            field=models.CharField(choices=[('BODA_ELECTRIC', 'Boda (Electric)'), ('BODA', 'Boda'), ('TUKTUK', 'Tuktuk'), ('CAB', 'Cab')], max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='FareRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(help_text='Flat fare in KSh')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.ForeignKey(blank=True, help_text='Optional; blank = applies to any vehicle (e.g. boda).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares', to='pricing.vehicletype')),
            ],
            options={
                'indexes': [models.Index(fields=['origin', 'destination'], name='pricing_far_origin_5968f1_idx')],
            },
        ),
    ]
