# Generated by Django 5.2.15 on 2026-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=16)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('WITHDRAWAL', 'Withdrawal'), ('PHONE_CHANGE', 'Phone change')], default='LOGIN', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'purpose'], name='accounts_ot_phone_n_bdbd97_idx')],
            },
        ),
    ]
