# Generated by Django 5.2.15 on 2026-06-21 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('BODA_STAGE', 'Boda stage'), ('TUKTUK_STAGE', 'Tuktuk stage'), ('CAB_RANK', 'Cab rank'), ('HUB', 'Hub / office'), ('LANDMARK', 'Landmark'), ('DEMAND', 'Demand hotspot'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
