# Generated by Django 5.2.15 on 2026-06-22 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_compliancedocument'),
        ('pricing', '0004_alter_vehicletype_code_fareroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_label', models.CharField(max_length=160)),
                ('dest_label', models.CharField(max_length=160)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('dest_lat', models.FloatField(blank=True, null=True)),
                ('dest_lng', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash')], default='MPESA', max_length=6)),
                ('base_fare', models.PositiveIntegerField(blank=True, null=True)),
                ('client_fee', models.PositiveIntegerField(default=0)),
                ('driver_fee', models.PositiveIntegerField(default=0)),
                ('client_total', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_payout', models.PositiveIntegerField(blank=True, null=True)),
                ('platform_cut', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('ARRIVING', 'Driver arriving'), ('ARRIVED', 'Driver arrived'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='pricing.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='trips_trip_status_4e1bc3_idx')],
            },
        ),
    ]
